### ISSUE TITLE
Search Suggestion for Home Page

### ISSUE THREAD

**Issue by unclebinary1001** [kprose07/MEDISCAN#15]

**Comment by unclebinary1001** [comment]
So, I have a working search suggestion for the home page, here's what it looks like

![studio64_nySFfiVKpn](https://user-images.githubusercontent.com/69122375/226072207-51be9237-c609-45eb-b6f7-b0bb85104a23.gif)

I'm working on raising a pull request for this soon after I configure my remote branch

**Comment by kprose07** [comment]
Cool I’m going to work on it around 9 today. I can also fix the styling etc of the search later. So do I pull from the master branch?

**Comment by unclebinary1001** [comment]
So, I haven't yet done the pull request. I'll let you know here once I do it later, I'm in the Techwise class 😄 . I'll also add a mention of the files I updated so you know where to start.

**Comment by kprose07** [comment]
Ok oof there was a class today? Yeah I might withdraw 🤦🏾‍♀️

**Comment by kprose07** [comment]
Made code for the text to ellipse:
                    <TextView
                        android:layout_width="103dp"
                        android:layout_height="30dp"
                        android:singleLine="true"
                        android:ellipsize="end"
                        android:background="@drawable/cardborderhome"

**Comment by kprose07** [comment]
Makes the cards look nice etc.. fixed the issue

https://user-images.githubusercontent.com/100654935/226081881-d8dd3eda-cb98-4107-9202-510bb3871ecd.mp4

**Comment by kprose07** [comment]
Found out how to use find all and replace.... Saved lot's of time : )
